# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: fuhaoshi@gmail.com
  email_provider_password: hohahaha
  domain_name: example.com
  secret_key_base: aeac997785854a8557be816daead92bcb050cd534cb5d7fffad2caf86212058138927c13b9ee0e26c842fe5a5ad0e6ffb7ebaa247e4e6f2414c6110f90d85448

test:
  domain_name: example.com 
  secret_key_base: cf275c35c920e5f23ac5bcdd4b964c7c3b71b23ae62b00cfdd80d0d387dec219e0a771af7672a38821c7b289734e43f19085a72b1ba41cbbe5f4ac031fdbfbde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: fuhaoshi@gmail.com
  email_provider_password: hohahaha
  domain_name: example.com
  secret_key_base: aeac997785854a8557be816daead92bcb050cd534cb5d7fffad2caf86212058138927c13b9ee0e26c842fe5a5ad0e6ffb7ebaa247e4e6f2414c6110f90d85448
